#!/usr/bin/env bash

set -euo pipefail

flags=(
    "-fshort-enums"
    "-fsingle-precision-constant"
    "-march=native"
    "-O0"
    "-static"
    "-Wall"
    "-Wcast-align"
    "-Wcast-align=strict"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdate-time"
    "-Wdouble-promotion"
    "-Wduplicated-branches"
    "-Wduplicated-cond"
    "-Werror"
    "-Wextra"
    "-Wfatal-errors"
    "-Wfloat-equal"
    "-Wformat-signedness"
    "-Wformat=2"
    "-Winline"
    "-Wlogical-op"
    "-Wmissing-declarations"
    "-Wmissing-include-dirs"
    "-Wnull-dereference"
    "-Wpacked"
    "-Wpedantic"
    "-Wpointer-arith"
    "-Wredundant-decls"
    "-Wshadow"
    "-Wstack-protector"
    "-Wswitch-enum"
    "-Wtrampolines"
    "-Wundef"
    "-Wunused"
    "-Wunused-macros"
    "-Wwrite-strings"
)

now () {
    date +%s.%N
}

# NOTE: Is there a nicer way to do this?
set +u
arg=${arg:="$1"}
set -u

if [ -n "$arg" ]; then
    cppcheck \
        --enable=all \
        --suppress=missingIncludeSystem \
        "$WD/src" \
        | sed 's/\/.*\/\(.*\) \.\.\./\1/g'
    clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
fi

(
    start=$(now)
    gcc "${flags[@]}" -o "$WD/bin/main" "$WD/src/main.c"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"
)

"$WD/bin/main" "$WD/code/main.asm" || echo $?
